### ISSUE TITLE
Read wlan sta info failed!

### ISSUE THREAD

**Issue by ZanderChang** [attify/firmware-analysis-toolkit#20]
When I press ENTER it start emulating the firmware. But it then traps into a dead cycle, which says 
`[  576.316000] firmadyne: ioctl: 0x6
[  576.316000] firmadyne: ioctl: 0x6
device ioctl:: Operation not supported
Read wlan sta info failed!`
again and again. But 192.168.0.1 works well.
What can I do to fix it ?

**Comment by extremecoders-re** [comment]
This is because firmadyne doesn't emulate the wifi peripherals. If the web interface is working as expected  you're good to go.

**Comment by ZanderChang** [comment]
OK, thanks a lot
