### ISSUE TITLE
Not working with Qemu 3.X 

### ISSUE THREAD

**Issue by amirdaly** [attify/firmware-analysis-toolkit#29]
Its not working with Qemu 3.X versions because there is no VLAN parameters in new version but it still use it for making network. is there any update for qemo 3?

**Comment by extremecoders-re** [comment]
FAT uses Firmadyne for emulation. At this time Firmadyne doesn't support Qemu 3.X yet.

Check https://github.com/firmadyne/firmadyne/issues/96
