### ISSUE TITLE
what is AttifyOS's password?

### ISSUE THREAD

**Issue by fIappy** [attify/firmware-analysis-toolkit#32]
what is AttifyOS's password?

**Comment by extremecoders-re** [comment]
This one?
https://github.com/adi0x90/attifyos

It's `attify123`

**Comment by fIappy** [comment]
> This one?
> https://github.com/adi0x90/attifyos
> 
> It's `attify123`

Thank you very much! I means this one  ,http://tinyurl.com/attifyos, which is mentioned by "In case you are on Kali and are facing issues with emulation, it is recommended to use the AttifyOS Pre-Release VM downloadable from here, or alternatively you could do the above mentioned."

**Comment by fIappy** [comment]
> > This one?
> > https://github.com/adi0x90/attifyos
> > It's `attify123`
> 
> Thank you very much! I means this one ,http://tinyurl.com/attifyos, which is mentioned by "In case you are on Kali and are facing issues with emulation, it is recommended to use the AttifyOS Pre-Release VM downloadable from here, or alternatively you could do the above mentioned."

I got it! It's password@123
