### ISSUE TITLE
expecting for password

### ISSUE THREAD

**Issue by paramikoooo** [attify/firmware-analysis-toolkit#41]
In this line 
https://github.com/attify/firmware-analysis-toolkit/blob/master/fat.py#L82
I got error because of pexpect wait for the password.

buffer (last 100 chars): b'Password for user firmadyne: '
before (last 100 chars): b'Password for user firmadyne: '
after: <class 'pexpect.exception.TIMEOUT'>

**Comment by extremecoders-re** [comment]
Can you check if this line in scripts/getArch.sh is commented.

https://github.com/firmadyne/firmadyne/blob/52fd43d81b4cbd377fc9b2ecbdc4472027701c48/scripts/getArch.sh#L88
 
If you have installed fat using the setup.sh script, it should have commented that line.

**Comment by extremecoders-re** [comment]
While installing fat using the setup.sh script, it automatically patches firmadyne such that the PostgreSQL database is not needed anymore.
