### ISSUE TITLE
Error : Brand doesn't exist 

### ISSUE THREAD

**Issue by Murthysagi** [attify/firmware-analysis-toolkit#5]
Hi,

When I try to run fat.py I am getting Below error 
<img width="1286" alt="1" src="https://cloud.githubusercontent.com/assets/16643148/24868050/8d94c256-1e2c-11e7-8f1c-a505892eacfd.png">

**Comment by adi0x90** [comment]
Did you run the setup and also started `postgresql` before running fat.py ?

**Comment by srikanthsaya** [comment]
Hi Aditya,

Facing the same problem even if PostgreSQL is running in the background...
<img width="1432" alt="screen shot 2017-08-27 at 10 13 25 pm" src="https://user-images.githubusercontent.com/31385945/29749909-895e8694-8b79-11e7-824e-39cb944fa249.png">
