### ISSUE TITLE
Location of dependency file has changed breaking setup script.

### ISSUE THREAD

**Issue by giffordiij** [attify/firmware-analysis-toolkit#74]
The installation scripts call for stuffit to be installed and the source file location has changed.  New location is in http://downloads.tuxfamily.org/sdtraces/BottinHTML/

But this breaks the install

**Comment by extremecoders-re** [comment]
This has been fixed upstream by removing the stuffit dependency totally.

Details: https://github.com/ReFirmLabs/binwalk/pull/615
