### ISSUE TITLE
Can't install FAT

### ISSUE THREAD

**Issue by asabhish** [attify/firmware-analysis-toolkit#78]
When I run the setup.sh script, the binwalk installation encounters an error "**fatal: Need to specify how to reconcile divergent branches**". I have installed binwalk separately via the apt repository and it works correctly. This looks like some git pull issue but I am not totally sure. How to resolve this? Attaching the screenshot of the tail-end of the installation log of FAT below:

![FAT_install_error](https://user-images.githubusercontent.com/93587364/195317634-f94ba10f-0283-4365-815c-56a55d4fa8ca.png)

**Comment by asabhish** [comment]
I could install FAT by commenting out the setup script portion which was installing binwalk tool. And I setup binwalk separately via apt repository. After setting the configuring firmadyne as per the instructions in FAT installation, now I am getting an error while creating the db in PostgreSQL. When I type in the command "**sudo -u postgres createdb -O firmadyne firmware**", the error I get is "**could not change directory to <my firmadyne directory path here>: Permission denied**" ! Any input here as to what is the solution here ? Thanks

**Comment by extremecoders-re** [comment]
The installation issue should be fixed with the latest commit.
