### ISSUE TITLE
no route to host

### ISSUE THREAD

**Issue by azraelxuemo** [attify/firmware-analysis-toolkit#79]
I use this firmware
ftp://ftp2.dlink.com/PRODUCTS/DIR-300/REVA/DIR-300_REVA_FIRMWARE_v1.06B05_WW.zip
![image](https://user-images.githubusercontent.com/60163868/200846765-dbc5a526-e2e3-4308-b7fc-7bcd6f09dd4e.png)
![image](https://user-images.githubusercontent.com/60163868/200846793-708dcea7-9727-4725-8963-1847d84f184b.png)
![image](https://user-images.githubusercontent.com/60163868/200846816-ebe46ada-5a8a-4307-8720-bde3d207f30d.png)
How to fix it

**Comment by extremecoders-re** [comment]
This happens due the bridge not being properly setup within the emulated firmwate.

Run this commands within firmadyne console and it should be reachable from host.

```
brctl show
brctl delif br0 eth2.0
ifconfig eth0 up
brcrtl addif br0 eth0
```

That is you need to delete whatever interface is currently attached on `br0` and then add the `eth0` interface.

**Comment by azraelxuemo** [comment]
Thank you very much for your help. It's really solved. Thank you for your kind answer. I hope this issue can help other people with the same confusion
