### ISSUE TITLE
fat.py and permission error

### ISSUE THREAD

**Issue by torabi12** [attify/firmware-analysis-toolkit#87]
Could you please help someone about this issue?
![kép](https://user-images.githubusercontent.com/98665813/217322739-870c1734-c6ae-4d91-a084-997883d3f1b3.png)

The same command used to work on my side but now it does not start.
I use Ubuntu-Mate 22.04.1 with latest packages.

**Comment by extremecoders-re** [comment]
Please run `./clean.py` first and delete the contents of the `images` directory if it isn't empty.
Then you can try running fat.py again.

**Comment by torabi12** [comment]
I run ./reset.py and I deleted the contents of the images folder but I got the same:
![kép](https://user-images.githubusercontent.com/98665813/217336090-5dc22ff1-2028-47c6-b3a0-66fb5f318df7.png)

I have no idea what has changed and caused this error. :(

**Comment by torabi12** [comment]
I tried again with sudo and not it is OK:
![kép](https://user-images.githubusercontent.com/98665813/217337964-c27080f2-8932-4d31-9db8-fd73ad8caa88.png)

and I was able to log into the web page of the firmware.

Thank you very much for your support!

**Comment by extremecoders-re** [comment]
Great to know that its working.

However fat.py shouldn't need sudo to run, it means the images directory is somehow owned by root.
