### ISSUE TITLE
Not working on ubuntu 17.04

### ISSUE THREAD

**Issue by Rumata888** [attify/firmware-analysis-toolkit#9]
I get the interface tap1_0, but 192.168.0.1 doesn't ping

**Comment by donniemillan** [comment]
I have the same issue with the same OS. It looks like the same issue everyone had here with Kali - https://github.com/attify/firmware-analysis-toolkit/issues/1, which has been closed 7 months ago with no resolution.

**Comment by adi0x90** [comment]
Let me check on 17.04 and get back with a working solution

**Comment by adi0x90** [comment]
Working fine for me with the Vanilla install of 17.04 and installing FAT. 

Can you share the entire console output and the output of `ip route list`
