### ISSUE TITLE
[help wanted] Cant ping from the Emulated to client

### ISSUE THREAD

**Issue by AnduinBrian** [attify/firmware-analysis-toolkit#94]
Hello i use FAT to emulate the WR841N device.
After i login, i got shell root. I start iptables to accept the connect:
```
iptables -F
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT
```
I can connect to web server from client and the client can ping the emulated router.
But on the router, i cant ping to client (192.168.0.2)
![Screenshot from 2023-12-21 15-23-30](https://github.com/attify/firmware-analysis-toolkit/assets/36282595/2954a041-8e59-400f-b021-066dfe342b0c)
But on the client, i can ping to the emulated router.
![Screenshot from 2023-12-21 15-25-03](https://github.com/attify/firmware-analysis-toolkit/assets/36282595/e0aba99d-1c61-413e-824d-c9c043479a9e)

I can ping from router to client when i emulated the NetGear D6000. So what actually happend in my case ?

**Comment by extremecoders-re** [comment]
Is there a firewall on the host which is preventing ping? 
In case if you already are able to achieve bidirectional communication it shouldn't be an issue.

Also please run `ifconfig`, `brctl` within the router and check the interfaces. Maybe there is no route or a misconfigured route which is preventing traffic from reaching the host.

**Comment by AnduinBrian** [comment]
My ufw is off.
There is no bidirectional communication because i cant connect to my tftp sv on the 0.2 client.
The router ifconfig
![image](https://github.com/attify/firmware-analysis-toolkit/assets/36282595/ebcc5247-bedb-4d92-a9e0-ee0b1b63ea99)
The client ifconfig
![image](https://github.com/attify/firmware-analysis-toolkit/assets/36282595/36510521-6c26-4c5d-b835-5b0f6afed040)
I tried to set the broadcast same as the router but still cant.

**Comment by AnduinBrian** [comment]
Found out, the IP range 192.168.0.1/24 is the problem.
I manualy delete the bridge and create a new one in the router (using `brctl`). After that i use `ifconfig` to set ip on both.
It worked.
