### ISSUE TITLE
git clone --quiet --depth 1 --branch master https://github.com/jrspruitt/ubi_reader warning: Could not find remote branch master to clone. fatal: Remote branch master not found in upstream origin

### ISSUE THREAD

**Issue by yqhao2002** [attify/firmware-analysis-toolkit#96]
git clone --quiet --depth 1 --branch master https://github.com/jrspruitt/ubi_reader
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin

**Comment by khaoticdude** [comment]
im running into this issue now :(
